@host=http://localhost:5065
@hostId=asdas
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjU2MjE3OC01YmMzLTQ1NjItOTcyZC0yOWM0NTNlYTEwNmQiLCJnaXZlbl9uYW1lIjoiRHlsYW4iLCJmYW1pbHlfbmFtZSI6IkNoZW4iLCJqdGkiOiJmZDY2YTk2My05ZWQ0LTRkMGEtYTJkYy1mMjFhNmNhMDk4ODAiLCJleHAiOjE3MDg3NTQyNTQsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.yEsJR95rYdpQilQJReJJja28oJeUUPncZPz4EpEj_c4
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Menu Name",
    "description": "Menu Description",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items":[
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}